project:
  type: website

website:
  title: "HERA – Health Economics & Regulatory Affairs Partner"
  favicon: images/favicon.png
  navbar:
    logo: images/hera_logo.png
    background: "#d6f5d6"
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: app.qmd
        text: HERA Application
      - text: "Resources"
        menu:
          - href: health-economics.qmd
            text: Health Economics
          - href: methods.qmd
            text: Methods & Validation
      - text: "Company"
        menu:
          - href: about.qmd
            text: About
          - href: contact.qmd
            text: Contact
  page-footer:
    background: "#d6f5d6"
    border: false
    left: |
      ![](images/hera_logo.png){width="100"}
    right: "© 2026 HERA Project – Health Economics & Regulatory Affairs Partner"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    number-sections: false
    highlight-style: github